language: java
sudo: required

services:
  - docker

branches:
  only:
    - master
    - develop

jdk:
  - oraclejdk8

script:
  - mvn package docker:build
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker push kholodovitch/marketing-personal-banner;
    fi
  - if [ "$TRAVIS_BRANCH" == "develop" ]; then
    docker push kholodovitch/marketing-personal-banner:dev;
    fi
